Update deploy GitHub Actions workflow
- Add more environment variables in the build step
- Add skips for some steps when using act
- Change job-wide environment variables
- Reformat some run scripts
- Reorder some steps
- Use new SLACK_CHANNEL secret

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,39 +11,51 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        os: [ubuntu-latest]
         node_version: [14.x]
     steps:
       - name: Check out
         uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node_version }}
-        uses: actions/setup-node@v2
-        with:
-          node-version: ${{ matrix.node_version }}
       - name: Set a job-wide environment variables
         run: |
           echo "APP_REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV
           echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
+          echo "DOCKER_IMAGE=victorpopkov/universal-redux" >> $GITHUB_ENV
+          echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
           echo "GITHUB_JOB_NAME=production" >> $GITHUB_ENV
-          echo "NODE_ENV=development" >> $GITHUB_ENV
           echo "NODE_VERSION=${{ matrix.node_version }}" >> $GITHUB_ENV
+      - name: Set up Node.js ${{ matrix.node_version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node_version }}
       - name: Install
         run: yarn install --ignore-scripts
+        env:
+          BABEL_ENV: development
+          NODE_ENV: development
       - name: Build
         id: build
         run: |
-          # build
           yarn build
           export STATUS="$?"
-
-          # status
-          if [ "${STATUS}" -eq 0 ]; then
-            exit 0
-          else
-            exit 1
-          fi
+          if [ "${STATUS}" -eq 0 ]; then exit 0; else exit 1; fi
         env:
+          # environment
+          BABEL_ENV: production
           NODE_ENV: production
+          # general
+          APP_BASE_PATH: /universal-redux
+          APP_HOST: 0.0.0.0
+          APP_PORT: 8080
+          APP_PUBLIC_PATH: /universal-redux/
+          # api
+          APP_API_PORT: 3030
+          APP_API_PROXY_DISABLED: 0
+          APP_API_PROXY_PATH: /api
+          APP_API_PROXY_TARGET: http://0.0.0.0:3030
+          APP_API_TARGET: http://0.0.0.0:3030
+          # other
+          NODE_PATH: ./src
+          UNIVERSAL_WEBPACK_CSS_LOADER_V4: true
       - name: Add Docker certificates to access the remote host
         run: |
           mkdir -p "${DOCKER_CERT_PATH}"
@@ -54,7 +66,7 @@ jobs:
           chmod 400 "${DOCKER_CERT_PATH}/cert.pem"
           chmod 400 "${DOCKER_CERT_PATH}/key.pem"
         env:
-          DOCKER_CERT_PATH: /home/runner/.docker/deploy
+          DOCKER_CERT_PATH: /home/runner/.docker/deploy/
           DOCKER_TLS_CA: ${{ secrets.DOCKER_TLS_CA }}
           DOCKER_TLS_CERT: ${{ secrets.DOCKER_TLS_CERT }}
           DOCKER_TLS_KEY: ${{ secrets.DOCKER_TLS_KEY }}
@@ -64,13 +76,10 @@ jobs:
             --tag="${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}" \
             --build-arg APP_REVISION=${APP_REVISION} \
             .
-          echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
-          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> $GITHUB_ENV
         env:
-          DOCKER_CERT_PATH: /home/runner/.docker/deploy
+          # docker
+          DOCKER_CERT_PATH: /home/runner/.docker/deploy/
           DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
-          DOCKER_IMAGE: victorpopkov/universal-redux
-          DOCKER_IMAGE_TAG: latest
           DOCKER_TLS_VERIFY: 1
       - name: Deploy Docker Stack
         run: |
@@ -82,25 +91,28 @@ jobs:
             --prune \
             "${DOCKER_STACK_NAME}"
         env:
-          DOCKER_CERT_PATH: /home/runner/.docker/deploy
+          # docker
+          DOCKER_CERT_PATH: /home/runner/.docker/deploy/
           DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
-          DOCKER_STACK_NAME: github_universal_redux
-          DOCKER_STACK_TRAEFIK_HOST: github.victorpopkov.com
-          DOCKER_STACK_TRAEFIK_NAME: github-universal-redux
-          DOCKER_STACK_TRAEFIK_PATH_PREFIX: /universal-redux/
           DOCKER_TLS_VERIFY: 1
+          # docker stack
+          DOCKER_STACK_NAME: github_universal_redux
+          # traefik
+          TRAEFIK_HOSTNAME: github.victorpopkov.com
+          TRAEFIK_NAME: github-universal-redux
+          TRAEFIK_PATH_PREFIX: /universal-redux/
       - name: Prepare success Slack notification
         if: success()
         run: echo "SLACK_CUSTOM_PAYLOAD=${SLACK_CUSTOM_PAYLOAD}" >> $GITHUB_ENV
         env:
-          SLACK_CUSTOM_PAYLOAD: '{"channel":"universal-redux","attachments":[{"color":"#2eb886","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has passed on Node.js {{ NODE_VERSION }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed on Node.js *{{ NODE_VERSION }}*"}}]}]}'
+          SLACK_CUSTOM_PAYLOAD: '{"channel":"${{ secrets.SLACK_CHANNEL }}","attachments":[{"color":"#2eb886","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has passed on Node.js {{ NODE_VERSION }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed on Node.js *{{ NODE_VERSION }}*"}}]}]}'
       - name: Prepare failure Slack notification
         if: failure()
         run: echo "SLACK_CUSTOM_PAYLOAD=${SLACK_CUSTOM_PAYLOAD}" >> $GITHUB_ENV
         env:
-          SLACK_CUSTOM_PAYLOAD: '{"channel":"universal-redux","attachments":[{"color":"#ed2f00","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has failed on Node.js {{ NODE_VERSION }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed on Node.js *{{ NODE_VERSION }}*"}}]}]}'
+          SLACK_CUSTOM_PAYLOAD: '{"channel":"${{ secrets.SLACK_CHANNEL }}","attachments":[{"color":"#ed2f00","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has failed on Node.js {{ NODE_VERSION }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed on Node.js *{{ NODE_VERSION }}*"}}]}]}'
       - name: Send Slack notification
-        if: always()
+        if: ${{ !env.ACT && always() }}
         uses: Ilshidur/action-slack@2.1.0
         env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
